name: .NET 5 CI
on: [push]

jobs:
  build:
    runs-on: windows-latest
    name: GTAW Chatlog Parser
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - run: dotnet build